- name: Configure web server 
  hosts: all
  become: true 
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
    
    - name: Create a deploy user
      user:
        name: deploy
        groups: wheel
        append: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install Nginx
      yum:
        name: nginx
        state: present 

    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - docker
    
    - name: Add deploy user to docker group
      user:
        name: deploy
        groups: docker
        append: yes
    
    - name: Harden SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      loop:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
      notify: 
        - Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted