---
- name: Configure web server
  hosts: all
  become: true
  vars:
    java_home: /usr/lib/jvm/java-11-amazon-corretto
  
  tasks:
    # System Updates
    - name: Update system packages
      yum:
        name: '*'
        state: latest

    # This is to ensure Ansible will use yum instead of dnf
    - name: Ensure yum is used
      yum:
        name: python38
        state: present
      vars:
        ansible_pakage_manager: yum

    # Java Installation
    - name: Install Java 11
      yum:
        name: 
          - java-11-amazon-corretto
          - java-11-amazon-corretto-devel
        state: present

    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME={{ java_home }}'
        create: yes

    # Jenkins Installation
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    # Docker Installation
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    # Web Server
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    # User Management
    - name: Create deploy user
      user:
        name: deploy
        groups: 
          - wheel
          - docker
        append: yes

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    # Essential Tools
    - name: Install Git
      yum:
        name: git
        state: present

    # Security Hardening
    - name: Secure SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      loop:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
      notify: restart_ssh

    # Information Display
    - name: Get Jenkins initial password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      ignore_errors: yes

    - name: Display access information
      debug:
        msg:
          - "Setup complete!"
          - "Jenkins: http://{{ ansible_default_ipv4.address }}:8080"
          - "Initial Jenkins password: {{ jenkins_password.content | b64decode | trim if jenkins_password.content is defined else 'Check /var/lib/jenkins/secrets/initialAdminPassword' }}"

  handlers:
    - name: restart_ssh
      systemd:
        name: sshd
        state: restarted